version: 2.1
executors:
  docker-publisher:
    environment:
      NODE_ENV: development # Needed if playwright is in `devDependencies`
    docker:
      - image: mcr.microsoft.com/playwright:bionic

jobs:
  node:
  working_directory: ~repo
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install npm dependencies
          command: |
            echo "Project endpoint - $FOLIO_JUNIT_OUTPUT_NAME"
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run tests
          command: |
            npm test

      - store_artifacts:
          path: ./test-results
      - store_artifacts:
          path: ./lib
