version: 2.1
executors:
  docker-publisher:
    environment:
      NODE_ENV: development # Needed if playwright is in `devDependencies`
    docker:
      - image: mcr.microsoft.com/playwright:bionic

jobs:
  node:
  working_directory: ~repo
  build:
    executor: docker-publisher
    parallelism: 2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            echo $(circleci tests glob tests/*spec.ts)
            circleci tests glob tests/*spec.ts | xargs -n 1 echo

      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run tests
          command: |
            npm test

      - store_artifacts:
          path: ./test-results
