version: 2.1
executors:
  docker-publisher:
    environment:
      NODE_ENV: development # Needed if playwright is in `devDependencies`
    docker:
      - image: mcr.microsoft.com/playwright:bionic

jobs:
  node:
  working_directory: /tmp
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Show Path
          command: |
            echo $PWD
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run tests
          command: |
            npm test

      - store_artifacts:
            path: /tmp/artifact-1
            destination: artifact-file

        - store_artifacts:
            path: /tmp/artifacts
